name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Run_test:
    runs-on: ubuntu-20.04 # Choosing OS
    strategy:
      matrix:
        node-version: [20.11.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      # trying to install npm packages
    - run: npm i
    - run: npx playwright install --with-deps 
    - name: run test
      # trying to run tests
      run: npx playwright test

    - name: Copy Allure data from previous runs
      run: |
        mkdir -p allure-results
        cp -R ${{ github.workspace }}/allure-results/ ./allure-results/ || true

    - name: Generate new Allure report
      run: npx allure generate --clean && npx allure open

    - name: Pull changes from the main branch
      run: git pull origin main

    - name: Push report to another branch
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout -b allure-report
        git add .
        git commit -m "Add new Allure report"
        git push origin allure-report
 
    - name: Setup GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
    