name: Run Playwright Tests and Publish Allure Report

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.1

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx playwright test

      - name: Copy Allure report data
        if: success()
        run: |
          if [ -d "allure-results" ]; then
            mkdir -p allure-results-previous
            cp -r allure-results/* allure-results-previous
          fi

      - name: Generate Allure report
        if: always()
        run: npx allure generate --clean

      - name: Push Allure report to another branch
        if: always()
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b allure-report
          git add -A
          git commit -m "Add Allure report"
          git push origin allure-report

      - name: Setup GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report